language: php
php:
    - "5.4"
    - "5.5"
    - "5.6"
    - "7.0"
    - "hhvm"

# Allow to use container infrastructure
sudo: false

cache:
  directories:
    - $HOME/.composer/cache

before_install:
    - phpenv config-rm xdebug.ini
    - echo -e "Host github.com\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
    - composer self-update --no-interaction

install:
    - sh -c 'if [ "$TRAVIS_PHP_VERSION" != "hhvm" ] && [ "$TRAVIS_PHP_VERSION" != "7.0" ]; then
        echo "extension = mongo.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini;
        fi;'
    - sh -c 'if [ "$TRAVIS_PHP_VERSION" = "hhvm" ] || [ "$TRAVIS_PHP_VERSION" = "7.0" ]; then
        composer remove --dev --no-update doctrine/mongodb-odm-bundle;
        fi;'
    - composer update --prefer-dist --no-interaction
    - ./app/console oro:requirejs:generate-config
    - ./app/console assets:install
    - npm install -g grunt-cli
    - npm install
    - curl http://get.sensiolabs.org/php-cs-fixer.phar -o php-cs-fixer

script:
    - ./bin/phpunit -c app/phpunit.travis.xml --testsuite PIM_Unit_Test
    - ./phpspec-fix
    - php php-cs-fixer fix --dry-run -v --diff --config-file=.php_cs.php
    - grunt travis

notifications:
  slack: akeneo:fDZaQeRRj1gVtXCW3f2kQAxo
